lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp, lib/Dialect/TritonGPU/Transforms/WSDataPartition.cpp, python/src/ir.cc, python/triton/compiler/code_generator.py, python/triton/language/__init__.py, python/triton/language/core.py
Pick from ws branch to match the functionality of ws branch.
Also keep taskId in AccelerateMatmul.cpp for gen5 gemm.
=> annotation support

include/triton/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVMBase.h
In the CPU mode, elementwise operations need to have vector types directly. Without this patch, an elementwise operation, even with vectors, was generated by multiple scalar operations. 
With this patch, a simple vector addition with masks has highly optimized code. `fadd` is with a vector type, and its two operands are also directly from two masked vector loads:
```
define void @kernel_add(ptr addrspace(1) nocapture readonly %0, ptr addrspace(1) nocapture readonly %1, ptr addrspace(1) nocapture writeonly %2, i32 %3, i32 %4, i32 %5, i32 %6, i32 %7, i32 %8, i32 %9) local_unnamed_addr #0 !dbg !3 {
%11 = shl i32 %4, 10, !dbg !6
%12 = insertelement <1024 x i32> poison, i32 %11, i64 0, !dbg !7
%13 = shufflevector <1024 x i32> %12, <1024 x i32> poison, <1024 x i32> <i32 poison, i32 0, i32 0, …
```
=> [ttm] Promote to vector types in elementwise operations

python/test/unit/language/test_core.py, python/triton/_internal_testing.py
=> [ttm][NFC] Change is_new_cpu to is_cpu

bin/RegisterTritonDialects.h, lib/Dialect/TritonGPU/Transforms/WSLowering.cpp, test/TritonGPU/amd/ws_lower.mlir, third_party/amd/backend/compiler.py, third_party/amd/include/TritonAMDGPUTransforms/Passes.h, third_party/amd/include/TritonAMDGPUTransforms/Passes.td, third_party/amd/lib/TritonAMDGPUTransforms/CMakeLists.txt, third_party/amd/lib/TritonAMDGPUTransforms/WSLowering.cpp, third_party/amd/python/triton_amd.cc
- Added TritonAMDGPUWSLoweringPass
- Lowering for GetAsyncTaskIdOp
=> [AMD] Add WSLowerPass and lower GetAsyncTaskIdOp

include/triton/Analysis/Allocation.h, lib/Analysis/Allocation.cpp, test/Analysis/test-allocation.mlir
Summary:
Upstream PRs:
https://github.com/triton-lang/triton/pull/5600
https://github.com/triton-lang/triton/pull/5595
=> [backport] SMEM allocation improvements

lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
Summary: make sure buffers are created in a deterministic way
=> try to make ttgir deterministic

lib/Dialect/TritonGPU/Transforms/WSDataPartition.cpp
Iterating taskid fix-up in data partition until all ops have consistent task id assignments.
=> [WS] Iterate taskid fixup in data partition

lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
During code split we need to know if a block arg is supposed to be duplicated into a specific task region. It isn't straightforward to get the task id of the arg from on IR as such id is not physically stored anywhere. All we have is the task id of its parent op which is likely a control op and shared by all tasks. The existing solution is to compute the task id for the arg based on its initial values. However, a block arg of an inner loop can be initialized by a block arg of an outer loop, which needs recursive upward tracking. We are doing it in another way that is to recursively downward track the user of the arg.
=> [WS] Recursive search for used args during code split

lib/Dialect/TritonGPU/Transforms/WSDataPartition.cpp
Fixing issues when slicing across N for ExpandDimsOp.
=> [DataPartition] Fix for slicing across N

lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
Summary: make sure buffers are created in a deterministic way
=> Pick from ws: try to make ttgir deterministic (#59)

lib/Dialect/TritonGPU/Transforms/WSDataPartition.cpp
When users specify to use more than one consumers to execute a code range, they implicate data partition. When data partition fails, the whole compilation should be terminated. Otherwise wrong number of threads will be created at runtime.
=> [DataPartition] Fail the compilation when partition fails

include/triton/Dialect/TritonGPU/Transforms/WSUtility.h, lib/Dialect/TritonGPU/Transforms/CMakeLists.txt, lib/Dialect/TritonGPU/Transforms/WSBuffer.cpp, lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp, lib/Dialect/TritonGPU/Transforms/WSUtility.cpp, python/tutorials/09-persistent-matmul.py
Also add WSUtility.h, WSUtility.cpp
=> [CodePartition] Move buffer related logic to WSBuffer

lib/Dialect/TritonNvidiaGPU/Transforms/TensorMemoryAllocation.cpp, test/TritonNvidiaGPU/test_tensor_memory_allocation.mlir
=> Fix TensorMemoryAllocation to correctly implement getAlloc (#6614)

lib/Dialect/TritonNvidiaGPU/Transforms/MMALowering.cpp
Summary: effectively reverting
Fixes thread mapping issue in llvm codegen (#64)
=> remove handling of async_task from MMALowering.cpp and MMAv5.cpp

python/test/unit/language/test_tlx.py, python/triton/compiler/code_generator.py, python/triton/tlx, setup.py, third_party/tlx/compiler/__init__.py, third_party/tlx/compiler/code_generator.py, third_party/tlx/compiler/dispatch.py, third_party/tlx/language/async_task.py, third_party/tlx/language/mem_ops.py, third_party/tlx/tutorials/vector-add2.py
TSIA
also including some linter fixes by pre-commit.
=> [TLX] Fix softlink error to third_party/tlx in setup.py

python/test/unit/language/test_tlx.py
=> [TLX] Enable testing for Blackwell

python/src/ir.cc, python/test/unit/language/test_tlx.py, third_party/tlx/language/__init__.py, third_party/tlx/language/barrier.py
Add `tlx.barrier_wait` and `tlx.barrier_arrive`
pytest python/test/unit/language/test_tlx.py -k test_mbarriers
=> [TLX] barrier_wait / barrier_arrive

lib/Conversion/TritonToTritonGPU/TritonGPUConversion.cpp
In general ttgir can be re-legalized if they are wrapped in a warp-specialization region introduced during later automatic warp specialization. Bailing out the whole ttgir dialect could cause issue there. I'm fixing it by special-casing ttgir ops in the legalization pass. 
Fixed the following test failures:
TRITON :: Conversion/relayout_tritongpu.mlir
TRITON :: TritonGPU/optimize-partition-warps.mlir
=> [TLX] Fix ttgir legalizing issue

python/src/ir.cc, python/test/unit/language/test_tlx.py, third_party/tlx/dialect/triton_tlx.cc, third_party/tlx/language/mem_ops.py
=> [TLX] Add local_load

README.md, python/test/unit/language/test_tlx.py
This PR updates the test with actual numerical checks and README
=> [TLX] Update local_load test and README

third_party/tlx/tutorials/pipelined-gemm.py
The compilation current fails at smem allocation due to unrecognized `tlx.required_layout` which should be handled by the layout propagation pass.
TTGIR before smem alloc: P1842819225
=> [TLX] Pipelined GEMM kernel for Hopper

third_party/tlx/language/utility.py, third_party/tlx/tutorials/pipelined-gemm.py
- Fixing wrong subscriptions and async_wait
- Enable loop unrolling for the prefetching loop to mitigate a missing opportunity with the redundant layout removal path
With additional config tuning:
M       N       K      cuBLAS      Triton
0  4096.0  4096.0  4096.0  590.130158  593.473448
=> [TLX] Fix somes issues with the tutorial GEMM 

third_party/tlx/tutorials/pipelined-gemm-blackwell-tma.py
Adapted auto tune configs from 09 GEMM tutorial.
With some hacky local patch to bypass layout propagation issues, I'm able to run this locally and there's a perf improvement compared to https://github.com/facebookexperimental/triton/pull/170, finally showing some four digit perf numbers:
```
✅ Triton and Torch match
Running benchmarks...
M       N       K       cuBLAS       Triton
0    256.0   256.0   256.0     4.112063     2.723574
1    384.0   384.0   384.0    13.770210     8.507077
2    512.0   512.0   512.0    29.433714    18.641351
3    640.0   640.0   640.0    57.487722    36.328160
4    768.0   768.0   768.0    98.991442    58.982401
5    896.0   896.0   896.0   140.933210    87.808000
6   1024.0  1024.0  1024.0   207.126128   124.275679
7   1152.0  1152.0 …
```
=> [TLX] Fine tune Blackwell TMA pipelined GEMM tutorial a bit

python/src/ir.cc, python/src/ir.h, python/triton/compiler/code_generator.py, python/triton/language/__init__.py, python/triton/language/core.py
Now that autoWS is in OSS/main, add support of "tl.async_task".
=> Add back support of async_task

third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSLowerMem.cpp
createTMEMCopy was removed from OSS when upstreaming, add it back.
=> Add back createTMEMCopy

third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSCodePartition.cpp
Summary: at later point of tailProducer or tmemStore
=> Fix taskId for producerAcquire, insert ProducerCommit in the right place

include/triton/Dialect/Triton/IR/Interfaces.h, lib/Dialect/Triton/IR/Dialect.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, test/TritonGPU/inline.mlir
Backporting upstream PR: https://github.com/triton-lang/triton/pull/6992
=> [TLX] Enable inlining in WS regions

third_party/tlx/tutorials/gemm-WS-hopper.py
Including the following optimizations:
- Improving L2 cache hit rate
- Recompute offsets in each working group to avoid capturing
- New tuning configs
- Epilog subtiling
```
M       N       K      cuBLAS      Triton
24  3328.0  3328.0  3328.0  530.811401  472.170816
25  3456.0  3456.0  3456.0  546.124071  511.882952
26  3584.0  3584.0  3584.0  575.458522  535.210671
27  3712.0  3712.0  3712.0  533.898116  467.424322
28  3840.0  3840.0  3840.0  570.337471  503.048186
29  3968.0  3968.0  3968.0  534.533328  517.804800
30  4096.0  4096.0  4096.0  568.530989  553.974877
```
=> [TLX] Tune WS gemm on hopper

python/test/unit/language/test_tlx.py
Local a group of tiles once all together., use them separately, and store them all together.
=> [TLX] Add a local_gather test

third_party/tlx/tutorials/gemm-WS-blackwell.py
See details in
- https://github.com/facebookexperimental/triton/pull/220
Need to pick to maintain both branches temporarily
=> Pick B200 GEMM tutorial in PR #220 from tlx-main branch

python/src/ir.cc, third_party/tlx/dialect/triton_tlx.cc, third_party/tlx/language/barrier.py, third_party/tlx/language/mem_ops.py
Enabling predication for TMA load/expect to allow writing more efficient pipelined code.
=> [TLX] Enable predication for TMA load/expect

python/test/unit/language/test_compile_errors.py
Picking from tlx branch
- https://github.com/facebookexperimental/triton/pull/242
`pytest -vs python/test/unit/language/test_tlx.py`  all pass.
`pytest -vs python/test/unit/language/test_compile_errors.py` all pass except a few pre-existing failures, which is not in tlx branch, and will be fixed separately.
=> Pick #242 [TLX] Fix failed test due to CompilationError wrapping

python/test/unit/language/test_conversions.py, python/test/unit/language/test_core.py, python/triton/_internal_testing.py
Prior PRs: 
- #227 
- #242 
This PR fixes the remaining test failures that have been validated by internal CI jobs. Hopefully that's all of it now.
=> [TLX] Fix remaining test failures caused by #227

third_party/amd/backend/compiler.py
Add tlx passes to AMD backend
Test: python  python/tutorials/01-vector-add.py
=> [AMD][TLX] Add tlx passes to AMD backend

python/test/unit/language/test_tlx.py
[TLX] Add reg load store test
Test:
python -m pytest  /home/kmanivannan/fb-triton/python/test/unit/language/test_tlx.py -k test_reg_only_load_store_smem
=> [TLX][test] Add reg load store test

python/setup.py
Reverts facebookexperimental/triton#270
=> Revert "Patch download file with chmod 777"

third_party/tlx/tutorials/blackwell-gdpa.py, third_party/tlx/tutorials/gdpa-blackwell.py
Need https://github.com/facebookexperimental/triton/pull/277 to run this tutorial.
=> [TLX][Tutorial] initial version of gdpa fwd on blackwell

python/test/unit/language/test_tlx.py
Test tl.dot with tlx shmem ops
Note: This test may fail for other shapes/kwargs until
reg->shared layout propagation is implemented tlx layout propagation
For the current inputs, this test passes on H100 and MI300
pytest  -s ~/fb-triton/python/test/unit/language/test_tlx.py -k test_tl_dot_with_tlx_smem_load_store
=> [TLX][test] Test tl.dot with tlx shmem ops

third_party/tlx/denoise.sh, third_party/tlx/run_all.sh, third_party/tlx/tutorials/blackwell-gdpa.py, third_party/tlx/tutorials/blackwell-gemm-pipelined.py, third_party/tlx/tutorials/blackwell-gemm-ws.py, third_party/tlx/tutorials/hopper-fa-ws-pipelined-pingpong_test.py, third_party/tlx/tutorials/hopper-fa-ws-pipelined_test.py, third_party/tlx/tutorials/hopper-fa-ws_test.py, third_party/tlx/tutorials/hopper-gemm-pipelined_test.py, third_party/tlx/tutorials/hopper-gemm-ws_test.py
TSIA
source: fbcode/triton/scripts/denoise.sh
`third_party/tlx/run_all.sh`
=> [TLX-3.5] Add LIT and denoise to run_all.sh

third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSCodePartition.cpp
Using simple heurisitcs:
- 1-D register tensor goes to a TMEM buffer
- MD tensor goes to SMEM
local_load/local_store are also added correspondingly.
=> [WS] Support lowering reg channel

third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSCodePartition.cpp
Summary: When there is a tma/gen5 channel, need to set the insertion point to be prior to the tma op.
=> [autoWS] Correctly set the insertion point for producerAcquire
