- lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
Summary: For an example with
IfOp
o = forOp
mulf that uses o
Prior to the change:
IfOp
o1 = forOp
mulf that uses o1
IfOp
o2 = forOp
mulf that uses o1
After:
IfOp
o1 = forOp
use o1
IfOp
o2 = forOp
use o2
We should not replace use of o with output of the specialized forOp while handling the first taskId, that will make handling of the next taskId incorrect. Instead of we update the mapping that is private to each taskId.
> fix an issue with two consumers when output of ForOp is used

- include/triton/Analysis/Allocation.h
- lib/Analysis/Allocation.cpp
Summary: Attempt to teach Allocation analysis to be aware of warpspec regions. Add a list of regions to each buffer, also teach interference graph to be ware of regions. Currently it makes convert_layout within one consumer to be able to overlap.
Test Plan: Run JFA bwd
> WarpSpec] improve allocation for smem

- lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
- test/TritonNvidiaGPU/WarpSpecialization/ws_code_partition.mlir
Fix the inefficient placement of consumer releases when producer and consumer are not in the same scope. For example, given
```
Q = tl.load
for (..) 
K = tl.load
QK = dot(Q, K)
...
tl.store
```
Previously the consumer release corresponding to `Q` was placed after the store. With the current fix the release would go right after the for loop.
`TORCH_CUDA_ARCH_LIST=9.0a python run.py --op flash_attention --only triton_tutorial_flash_v2_tma_ws,triton_tutorial_flash_v2_tma_ws_persistent,triton_tutorial_flash_v2 --num-inputs 1 --seq-len 10 --metrics tflops --batch 1024 --n-heads 4 --d-head 128 --cudagraph`
Before:
```
(Batch, Heads, SeqLen, Dhead)    triton_tutorial_flash_v2_tma_ws-tflops    triton_tutorial_flash_v2_tma_ws_persistent-tflops    triton_tutorial_flash_v2-tflops …
```
> [CodePartition] Optimize the placement of consumer releases 

- lib/Dialect/TritonGPU/Transforms/WSLowering.cpp
Having each thread run the consumer release operation simplifies the logics by avoiding master thread id computation. This seems to help improve performance a bit.
- 2% speedup for triton_tutorial_flash_v2_tma_ws
- 0.3% speedup for matmul_layernorm_ws
> [WSLowering] consumer release on each thread instead of master thread

- include/triton/Analysis/Allocation.h
- include/triton/Tools/Sys/GetEnv.hpp
- lib/Analysis/Allocation.cpp
- lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
- test/TritonNvidiaGPU/WarpSpecialization/ws_code_partition.mlir
location
Summary: We already have channelsGroupedByProducers and channelsGroupedByConsumers. For one-producer-multi-consumer mode, a single buffer will be used, channelsGroupedByProducers is used for this. channelsGroupedByConsumers is to minimize the insertion of sync primitives, a single set of communication ops will be inserted.
For this patch, we want to share the same smem location for multiple channels that are live in different loop nests. We add allocation.shareGroup attributes to the local_allocs corresponding to channels that reuse the same smem location.
In order to reuse the same smem location, we update bufferIdx and phase through all the loop nests that share smem locations. We handle the following cases:
```
for # persistent loop
for # can be nested under if
for # can be …
```
> [WarpSpec] add support for multiple channels sharing the same smem

- lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
Summary: When running hstu with multi-target, we have: IfOp
thenBlock:
opA (taskId 1)
opB (taskId 2)
Yield resOpA resOpB
elseBlock:
Op uses output of IfOp
In this case, when specializing IfOp for taskId 1, we should remove some of the results
IfOp (taskId 1)
thenBlock:
opA (taskId 1)
Yield resOpA
elseBlock:
> [CodePart] fix results of specialized IfOp

- include/triton/Dialect/TritonGPU/Transforms/Passes.td
- lib/Dialect/TritonGPU/Transforms/CMakeLists.txt
- lib/Dialect/TritonGPU/Transforms/TaskIdPropagate.cpp
- lib/Dialect/TritonGPU/Transforms/WSTaskPartition.cpp
- python/src/passes.cc
- python/tutorials/10-warp-specialized-matmul.py
- test/TritonNvidiaGPU/WarpSpecialization/ws_task_partition.mlir
- third_party/nvidia/backend/compiler.py
We are taking a simple heuristic alternative to user annotation to separate memory loads that are connected to a heavy dot operation into the producer group, while leaving everything else in the consumer groups. This appears to cover important kernels such as GEMM, FA, HSTU.
With this there is no user annotations required in the kernel code to enable WS. User just needs to specify some flags in the autotune configs to trigger WS, .e,g.,`num_consumer_groups` and `num_buffers_warp_spec`
triton.Config(
{
"BLOCK_SIZE_M": 128,
"BLOCK_SIZE_N": 256,
"BLOCK_SIZE_K": 64,
"GROUP_SIZE_M": 8,
"NUM_CONSUMER_GROUPS": 2,
},
num_stages=2,
num_warps=4,
num_consumer_groups=2,
num_buffers_warp_spec=3,
),
> Automating warp-group partition

- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp
Small TMA store only needs the first warp to issue the TMA store instruction instead of having all warps issue one. For WS, the first warp should be the first one of the current warp group instead of hardcoded 0. 
Thanks @ggengnv for helping investigate an illegal instruction issue caused by the bug!
> Fix an issue where wrong warp id is used for small TMA store

- lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
Summary: In this case, we don't need to generate accumLoopCount for the IfOp. The current sharing logic only supports sharing across double-nested loops.
> [buffer reuse] fix the case of If + For + For

- lib/Dialect/TritonGPU/IR/Dialect.cpp
Summary: Use PatternRewriterWithAsyncTaskIds instead of setAttrs(getAttrs). getAttrs can cause issue if op is destroyed.
> Fix segfault when updating attributes

- lib/Dialect/TritonGPU/Transforms/WSDataPartition.cpp
Adding `FpToFpOp` to `WSDataPartition` pass. Currently `TritonGPUWSDataPartition` pass fails since the `sliceOp` is missing support for `FpToFpOp` and results in "Unsupported Op type" error.
Sample failing IR:
```
[tritongpu-warp-spec-data-partition]: slicing:
%58 = "tt.fp_to_fp"(%52) <{rounding = 1 : i32}> {async_task_id = dense<[1, 2]> : vector<2xi32>} : (tensor<128x128xf32, #triton_gpu.nvidia_mma<{versionMajor = 3, versionMinor = 0, warpsPerCTA = [4, 1], instrShape = [16, 128, 32]}>>) -> tensor<128x128xf8E5M2, #triton_gpu.nvidia_mma<{versionMajor = 3, versionMinor = 0, warpsPerCTA = [4, 1], instrShape = [16, 128, 32]}>>
[tritongpu-warp-spec-data-partition]:
unsupported op type
```
Verified the pass succeeds after adding `FpToFpOp` using `triton-opt`
Test command used:
``` …
```
> [WS] Add FpToFpOp to WSDataPartition pass

- lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
This handles the case of reuse between parallel IfOp and ForOp. Prior to this, we only allow buffer reuse across parallel ForOps.
> Support buffer reuse between ForOp and IfOp

- lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
- lib/Dialect/TritonGPU/Transforms/WSDataPartition.cpp
Handling the nested if in a loop that used one loop arg in its yield, e.g. %arg20 below. `%arg20` and its initial value `%43` should be included in the consumer slice.
```
%43 = arith.mulf %35, %41 {async_task_id = dense<[0, 1, 2]> : vector<3xi32>} : tensor<128xf32, #blocked> loc(#loc34)
%45:5 = scf.for %arg17 = %c0_i32 to %13 step %c1_i32 iter_args(%arg18 = %c0_i32, %arg19 = %cst_0, %arg20 = %43, %arg21 = %cst_0, %arg22 = %44) -> (i32, tensor<128x128xf32, #mma>, tensor<128xf32, #blocked>, tensor<128x128xf32, #mma>, tensor<128xf32, #blocked>)  : i32 {
%61:2 = scf.if %60 -> (tensor<128xf32, #blocked>, tensor<128xf32, #blocked>) {
scf.yield {async_task_id = dense<[1, 2]> : vector<2xi32>} %arg20, %arg22 : tensor<128xf32, #blocked>, tensor<128xf32, #blocked> loc(#loc1)
} else {
...
%82 = …
```
> Handle if results that are connected to a block arg

- lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
- python/test/unit/language/test_core.py
https://github.com/triton-lang/triton/pull/5469 introduced a support for dot operations using FMA via linear layout. It benefits the CPU mode as well. It's not fully working. There are some issues:
- It looks like [The FMA code](https://github.com/triton-lang/triton/blob/ac9574c4d8544005ebc875c9ab99c1333080a808/lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/FMA.cpp#L23) does not consider integers and mixed types like `fp16` and `fp32`. It needs a proper type promotion.
- For the performance and compilation time, we need to directly emit FMAs with vector types?
Nonetheless, we now see some basic dot operations are working.
> [ttm] Introduce an initial support for dot operations

- include/triton/Dialect/TritonGPU/Transforms/Passes.td
- include/triton/Tools/Sys/GetEnv.hpp
- lib/Dialect/TritonGPU/Transforms/CMakeLists.txt
- lib/Dialect/TritonGPU/Transforms/PingPong.cpp
- python/src/passes.cc
- third_party/nvidia/backend/compiler.py
Initial preliminary implementation for PingPong across the two consumer warp groups. This assumes the consumer warp groups execute the same code, and the pass will try to figure out cuda core region vs. tensor core region and insert named barriers to synchronize across the consumer warp groups. When one consumer warp group is in cuda core, the other should be in tensor core.
The pass is guarded with env variable ENABLE_PINGPONG.
> [WS] add pingpong pass

- python/test/unit/language/test_core.py
Okay, for faster test_core.py iterations, I added more skips and filtering to avoid long compilation time.
On a super-duper 384 machine, it now runs in 5 minutes. Yeah, I know it fails a lot, but we will get to that later.
```
> % TRITON_CPU_BACKEND=1 python3 -m pytest -n 380 "python/test/unit/language/test_core.py" --device cpu -m cpu
...
FAILED python/test/unit/language/test_core.py::test_precise_math[1-tl.math.sqrt_rn(x)-tl.math.sqrt(x.to(tl.float64)).to(tl.float32)] - RuntimeError: PassManager::run failed
FAILED python/test/unit/language/test_core.py::test_precise_math[1-tl.math.div_rn(x,y)-(x.to(tl.float64) / y.to(tl.float64)).to(tl.float32)] - RuntimeError: PassManager::run failed
FAILED python/test/unit/language/test_core.py::test_math_erf_op[float32] - RuntimeError: Failed to …
```
> [ttm] Adjust test_core.py mostly to skip long compilation

- lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
- test/TritonNvidiaGPU/WarpSpecialization/ws_code_partition.mlir
Summary:
With arbitary data channel the producer ops could be a non-load op, which mean it doesn't necessarily write to SMEM. A `local_store` op will be created to support the data channel, and in that case the producer acquire primitive should precede the `local_store` op instead of the original producer op. This change enables that by creating the async copy before inserting synchronization primitives. A map is set up to track the created async copy and the original data channel.
> [CodePartition] Insert synchronization ops after asycn copy creation.

- lib/Dialect/TritonGPU/IR/Ops.cpp
- lib/Dialect/TritonGPU/Transforms/WSDataPartition.cpp
- lib/Dialect/TritonNvidiaGPU/Transforms/TMALowering.cpp
tmem_load, tmem_alloc can have side effects so we can no longer depend on populateForOpDeadArgumentElimination/ForOp cleanup to remove the original ops that should be replaced with the sliced versions. We removed the original ops by walking through the function op and erasing ops in partitionScheme.ops.
Also this patch tries to correctly handle the slicing of tmem_load/alloc: an extra convert_layout is added to convert the blocked layout that is used by tmem_load/alloc to be compatible with the sliced tmem.
There are a few places where we need to keep attributes. These changes exist in the ws branch but in a different file.
> [Blackwell][WS] Improve data partitioning to handle tmem_load/alloc

- lib/Dialect/TritonGPU/Transforms/TaskIdPropagate.cpp
`TaskIdPropagate` pass fails when there is not `dotOp`. 
Currently the `populateTaskIdsForControlDependencies` is called even when `anchorOps` are empty, which is the case for non-warp specialized kernel blocks.
This change bails out of task id propagation when `anchorOps` is empty.
> [WS] Skip task id propogation in absence of dot op

- lib/Dialect/TritonGPU/Transforms/WSDataPartition.cpp
When in the presense of `tl.trans`, the original partition dimension could flip. I'm extending data partition to support per-op partition dimension. This requires a DFS-based partition scheme computation instead of a BFS one.
I'm also extending partition computation to be iterative, i.e, when a paricular partition either along M or N dimension fails, it automatically tries partition along the other dimension.
> [DataPartition] Support per-op partition dimension

- lib/Dialect/TritonGPU/Transforms/WSDataPartition.cpp
Ops in a slice can have different async task ids such as
```
%cst = arith.constant {async_task_id = dense<[0, 1, 2]> : vector<3xi32>} dense<0.000000e+00> : tensor<128x256xf32, #blocked> loc(#loc1)
%31 = ttng.tmem_alloc %arg8 {async_task_id = dense<[1, 2]> : vector<2xi32>} : (tensor<128x256xf32, #blocked>) -> !ttg.memdesc<128x256xf32, #tmem, #ttng.tensor_memory, mutable> loc(#loc27)
```
Use a separate IR builder per op to avoid the mixing of task ids.
> [DataPartition] Use per-op IR builder during slicing

- lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
Summary:
For the case of
```
ForOp
IfOp
ForOp
Channel
```
We need to create AccumLoopCount for the channel through the outer ForOp. Prior to the fix, bufIdx argument of the outer loop increases by one for each iteration, which can cause deadlock when the IfOp is not executed for some iterations.
The fix is to add AccumIf argument for the outer ForOp:
```
ForOp accumIf, bufIdx
IfOp
ForOp
Channel uses (idx, phase) based on accumIf
accumIf += 1
```
Modify createNewLoop to handle the general case instead of depending on
bool hasParallelReuse, bool isOuterOfReuse.
> Update bufferIdx correctly to handle IfOp under ForOp

- lib/Dialect/TritonGPU/Transforms/WSDataPartition.cpp
- test/TritonNvidiaGPU/WarpSpecialization/ws_data_partition.mlir
Previously we only support data partition an operation along a fixed dimension, i.e, either M- or N-dim for a 2D tensor operation. Now I'm extending it to supporting partition an op along multiple dimensions. A specific use case is to partition along a chain of dot operations. E.g.,
```
o = tl.dot(o, w)
grad_o = tl.dot(grad_o, tl.trans(w))
grad_w = tl.dot(tl.trans(grad_o), o)
tl.atomic_add(grad_w)
```
Partitioning the first dot along `M` would lead to partitioning the third dot along `K`. Partitioning the first do along `N` would result in partitioning the second dot along `K`. Either way would cause a cross-dimension partition (K-partition) for the two operands of some dot and it is only valid when the immediate result of the K-partitioned dot is stored out through an atomic_add. The PR …
> [WS] Support cross-dimension split-K data partition

- python/triton/language/core.py
Also support specifying task_id with `const_expr` values, such as
```
@triton.jit
def kernel(ptr, CONSUMER_TASK: tl.constexpr):
with tl.async_task([CONSUMER_TASK]):
tl.store(...)
```
Also deduplcating task ids specified with  tl.async_task, e.g
```
with tl.async_task([1, NUM_CONSUMER_GROUPS]):
tl.store(...)
```
> [WS] Deduplicate tl.async_task

- lib/Dialect/TritonGPU/Transforms/WSDataPartition.cpp
For a loop argument of which the initial value is a result of another region, the following mapping could is gonna give the exactly same initial value instead of the sliced value. Switching to mapping lookup as a fix.
```
auto initArgOp = initArg.getDefiningOp();
unsigned resultIndex = cast<mlir::OpResult>(initArg).getResultNumber();
newInitArg = newInitArgOp->getResult(resultIndex);
```
> [DataPartition] Fix loop arg partition issue

- lib/Dialect/TritonGPU/Transforms/Pipeliner/SoftwarePipeliner.cpp
- lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
- python/gemmbench/gemmbench.py
- python/gemmbench/impls/matmul_persistent_tma_ws.py
- python/tutorials/09-persistent-matmul.py
- test/TritonNvidiaGPU/WarpSpecialization/ws_code_partition.mlir
- third_party/nvidia/backend/compiler.py
The tcgen05 mma instruction can update an inline barrier object on this completion. The implementation of consumer release can leverage that efficiently.
The most performant WS gemm kernel now is with two workgroups:
```
Barrier p[3],c[3];
if warp_id == [0,3]:  
for k in range(0, tl.cdiv(K, BLOCK_K), phase=1, idx=0):
ProducerAcquire(c[idx], phase)
a[idx] = tl._experimental_descriptor_load(a_ptrs, p[idx])
b[idx] = tl._experimental_descriptor_load(b_ptrs, p[idx])     
a_ptrs += BLOCK_K * stride_ak
b_ptrs += BLOCK_K * stride_bk
phase = (idx < 2) ? phase : phase ^ 1 
idx = (idx + 1) % 3     
if warp_id == [4,7]:  
c1 = tl.zeros((BLOCK_M / 2, BLOCK_N))
for k in range(0, tl.cdiv(K, BLOCK_K), phase=0, idx=0):
ConsumerWait(p[idx], phase)
c1 += tl.dot(a1[idx], b[idx], c[idx])
phase = (idx < 2) ? …
```
> [WS][Blackwell] Use mma inline barrier for consumer release

- include/triton/Dialect/TritonGPU/Transforms/Utility.h
- include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUAttrDefs.td
- lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
- python/gemmbench/impls/matmul_persistent_tma_ws.py
- python/tutorials/09-persistent-matmul.py
- test/TritonNvidiaGPU/WarpSpecialization/ws_code_partition.mlir
Enable a third warp group to do the epilog job:
```
Barrier p[3],c[3], tp[2], tc[2]
if warp_id == [0,3]:  
for k in range(0, tl.cdiv(K, BLOCK_K), phase=1, idx=0):
ProducerAcquire(c[idx], phase)
a[idx] = tl._experimental_descriptor_load(a_ptrs, p[idx])
b[idx] = tl._experimental_descriptor_load(b_ptrs, p[idx])     
a_ptrs += BLOCK_K * stride_ak
b_ptrs += BLOCK_K * stride_bk
phase = (idx < 2) ? phase : phase ^ 1 
idx = (idx + 1) % 3     
if warp_id == [4,7]:  
ProducerAcquire(tc[outer_idx], outer_phase)
tmem_store(c1[outer_idx], 0)
for k in range(0, tl.cdiv(K, BLOCK_K), phase=0, idx=0):
ConsumerWait(p[idx], phase)
c1 += tl.dot(a1[idx], b[idx], c[idx])
phase = (idx < 2) ? phase : phase ^ 1
idx = (idx + 1) % 3
ProducerCommit(tp[outer_idx])
if warp_id == [8,11]:  
ConsumerWait(tp[outer_idx], …
```
> [WS][Blackwell] Double buffering TMEM

- lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
- python/test/unit/language/test_core.py
[BACKEND] Functional fixes for layout conversion that uses `stmatrix` (#5407)
This PR:
1. Refactored construction logic in `LinearLayoutConversions.cpp` for `stmatrix` selection. Note that the heuristic-based approach will be replaced with LL-driven approach once we have `divideRight` and `divideLeft`.
2. Updated `SharedLayout` class and added `has_leading_offset` attribute.
3. Added comprehensive new test cases for MMA and shared layouts.
Tested by running `python python/gemmbench/gemmbench.py`. Specifically `matmul_tma_ws.py` was failing and now is passing.
> Pick commit into ws branch to fix LinearLayout for stmatrix

- lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
In createToken, only one consumer group can use the gen5 barrier. If two consumer groups feeding the same gen5 dotOp both use consumer barrier, we will create two different consumer barriers for the two consumer groups, and the gen5 barrier will pick one of the consumer barriers, the other consumer barrier will deadlock.
Also fix the merging condition:
Consider the case where channel v is between producer task 0 and consumer task 1, while channel p is between producer task 2 and consumer task 1, if we merge these two channels in groupByConsumer, in createToken, we only consider the first channel in the group, thus ignoring the different producer taskId.
> [WS] can't use the same gen5 barrier for two channels in two different groups

- lib/Dialect/TritonGPU/Transforms/WSCodePartition.cpp
So subview/bufferIdx has the correct taskIds. It also handles the case where tmem_alloc doesn't have a srcValue.
For TMEM channel feeding into operand A of gen5 dotOp, we set up TokenLoadType correctly.
> Clean up taskIds in createTMEMCopy

- include/triton/Analysis/TaskIdPropagation.h
- lib/Analysis/CMakeLists.txt
- lib/Analysis/TaskIdPropagation.cpp
- lib/Dialect/TritonGPU/Transforms/TaskIdPropagate.cpp
- lib/Dialect/TritonNvidiaGPU/Transforms/Utility.cpp
- test/TritonNvidiaGPU/WarpSpecialization/async_propagate.mlir
This diff refactors the current TaskIdPropagate pass using MLIR's sparse backward dataflow analysis.
Advantages:
- Using a more robust upstream analysis.
- TaskId lattices are on granularity level of SSA values instead of whole ops (At the end of the propagation they are still dumped as annotations on op level for now due to later passes expecting it that way. This will be addressed in a larger overhaul).
> [WS] Refactor TaskIdPropagate pass

- python/src/ir.cc
- python/triton/compiler/code_generator.py
- python/triton/tlx
- setup.py
- third_party/tlx/README.md
- third_party/tlx/__init__.py
- third_party/tlx/compiler/__init__.py
- third_party/tlx/compiler/code_generator.py
- third_party/tlx/compiler/dispatch.py
- third_party/tlx/language/__init__.py
- third_party/tlx/language/async_task.py
TLX (Triton Low-level Language Extensions) is a low-level, warp-aware, hardware-near extension of the Triton DSL. It provides intrinsics and warp-specialized operations for fine-grained GPU control, hardware-oriented primitives for advanced kernel development, and explicit constructs for GPU memory, compute, and asynchronous control flow, designed for power users pushing Triton to the metal.
This PR adds scaffolding for TLS and introduces async task related ops for warp specialization support through explicit async task programming
```
@triton.jit
def add_kernel(x_ptr, y_ptr, output_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
pid = tl.program_id(axis=0)
block_start = pid * BLOCK_SIZE
offsets = block_start + tl.arange(0, BLOCK_SIZE)
mask = offsets < n_elements
x_buf = …
```
> [TLX] Introducing Triton low-level language extension

- lib/Conversion/TritonToTritonGPU/TritonGPUConversion.cpp
- lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
- test/Conversion/triton_to_tritongpu.mlir
- third_party/tlx/tutorials/vector-add2.py
Also added a tutorial 
```
@triton.jit
def add2_warp_specailized_kernel(
x_ptr,
y_ptr,
z_ptr,
a_ptr,
b_ptr,
c_ptr,
n_elements,
BLOCK_SIZE: tl.constexpr,
):
pid = tl.program_id(axis=0)
block_start = pid * BLOCK_SIZE
with tlx.async_tasks():
with tlx.async_task("default"):
offsets = block_start + tl.arange(0, BLOCK_SIZE)
mask = offsets < n_elements
x = tl.load(x_ptr + offsets, mask=mask)
y = tl.load(y_ptr + offsets, mask=mask)
output = x + y
tl.store(z_ptr + offsets, output, mask=mask)
with tlx.async_task(num_warps=4):
offsets = block_start + tl.arange(0, BLOCK_SIZE)
mask = offsets < n_elements
a = tl.load(a_ptr + offsets, mask=mask)
b = tl.load(b_ptr + offsets, mask=mask)
output = a + b
tl.store(c_ptr + offsets, output, mask=mask)
```
vector-add-performance (gbps):
```
size       Triton …
```
> [TLX] Enable legalizing WarpSpecializeOp during TTIR->TTGIR

- include/triton/Dialect/Triton/IR/TritonOps.td
- python/src/ir.cc
- python/triton/language/core.py
- python/triton/language/semantic.py
Adding a latency variable in the load op which can be used in the future for latency described pipelining & scheduling.
Added an optional int in the load op and modified related functions.
[rules](https://cbea.ms/git-commit/#why-not-how).
- [] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.
- Select one of the following.
- `/test` for `lit` tests
- `/unittest` for C++ tests
- `/python/test` for end-to-end tests
- [x ] This PR does not need a test because no functionality has been added so far, only exposed an optional variable.
- Select one of the following.
including the "tests should be minimal" section. (Usually running Python code
and using the instructions it generates is not minimal.)
> Exposing latency on the load

- python/src/ir.cc
- python/test/unit/language/test_tlx.py
- third_party/tlx/language/__init__.py
- third_party/tlx/language/mem_ops.py
- third_party/tlx/language/types.py
This PR adds buffer indexing capability.
For the `local_alloc_index` kernel in `test_tlx.py`, IR looks like below:
```mlir
#shared = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [0]}>
#smem = #ttg.shared_memory
"builtin.module"() ({
"tt.func"() <{arg_attrs = [{tt.divisibility = 16 : i32}, {tt.divisibility = 16 : i32}, {tt.divisibility = 16 : i32}], function_type = (!tt.ptr<f32>, !tt.ptr<f32>, i32) -> (), sym_name = "local_alloc_index", sym_visibility = "public"}> ({
^bb0(%arg0: !tt.ptr<f32> loc(unknown), %arg1: !tt.ptr<f32> loc(unknown), %arg2: i32 loc(unknown)):
%0 = "ttg.local_alloc"() : () -> !ttg.memdesc<2x256x256xf32, #shared, #smem> 
%1 = "arith.constant"() <{value = 0 : i32}> : () -> i32 
%2 = "ttg.memdesc_subview"(%0, %1) : (!ttg.memdesc<2x256x256xf32, …
```
> [TLX] Add buffer indexing

- python/src/ir.cc
- python/test/unit/language/test_tlx.py
- third_party/tlx/language/__init__.py
- third_party/tlx/language/utility.py
A `threadId` op allows users to write thread-specialization code which could ease debugging.
> [TLX] tlx.thread_id support

- README.md
- python/src/ir.cc
- python/test/unit/language/test_tlx.py
- python/triton/tlx
- third_party/tlx/language/__init__.py
- third_party/tlx/language/barrier.py
- third_party/tlx/language/types.py
This PR adds new op `tlx.barrier_expect` with a few minor changes included as below:
1. combine `tlx.mbarriers` with `tlx.buffered_tensor`
2. minor fix in `create_memdesc_subview` because barrier alloc must be a descriptor of 1xi64 type
Going forward:
1. add a few more barrier ops (wait/arrives) in separate PRs for easier review
2. finish a complete GEMM showcase with tlx primitives
3. add validator logics in ops
> [TLX] Add tlx.barrier_expect plus some minor formatting

- python/src/ir.cc
- `tlx.local_alloc` should return a mutable memory buffer
- When creating a `MemDescSubviewOp`, the offset should have the same dimensions as the buffer shape.
> [TLX] Fix local_alloc and memdesc_subview issues

- python/src/ir.cc
- python/test/unit/language/test_tlx.py
- third_party/tlx/language/mem_ops.py
- third_party/tlx/language/types.py
Introducing shared memory layout encoding during buffer allocation. User can optionally specify the explicit encoding (not implemented yet), otherwise the compiler enforces a non-swizzled layout for the buffer.
When the buffer is used in a different layout, e.g, a non-swizzled buffer is used for dot operands, layout conversion will be needed. Assigning layout information to `tlx.buffered_tensor` ensures a strong type system that can identify the need of such layout conversion.
> [TLX] Introducing shared memory layout encoding

- python/test/unit/language/test_compile_only.py
- python/test/unit/runtime/test_autotuner.py
- python/triton/compiler/code_generator.py
- python/triton/runtime/autotuner.py
- third_party/amd/backend/driver.py
Backports the changes from the following commits:
- https://github.com/triton-lang/triton/commit/ba2d7f5276bb48d516245be10317c4b6896944b2
- https://github.com/triton-lang/triton/commit/3bd4a58ae718f7383737b05bd8a6531f7a76d9c6
- https://github.com/triton-lang/triton/commit/1e914b7584ba5781a7f1399d3ef6975d6327cedb
These were resolved in Beta/Trunk testing to fix issues related to building Triton on CPUs and either defining or importing kernels.
> Backport changes to resolve do_bench/cpu related isuses

- README.md
- python/test/unit/language/test_tlx.py
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/__init__.py
- third_party/tlx/language/mem_ops.py
- third_party/tlx/language/types.py
- third_party/tlx/language/utility.py
Extending  `tlx.local_alloc` to handle tensor memory allocation on Blackwell:
- `buffers = tlx.local_alloc(shape, dtype, num_buffers)`  # to allocate buffer on shared memory
- `buffers = tlx.local_alloc(shape, dtype, num_buffers, tlx.storage_kind.smem)`  # to allocate buffer on shared memory
- `buffers = tlx.local_alloc(shape, dtype, num_buffers, tlx.storage_kind.tmem)`  # to allocate buffer on tensor memory
> [TLX] Tensor memory allocation support

- README.md
- python/test/unit/language/test_tlx.py
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/__init__.py
- third_party/tlx/language/mem_ops.py
- third_party/tlx/language/types.py
Introducing two synchronization operations that can be used to track the completion of `tlx.async_load`
- `tlx.async_load_commit_group(tokens)`
Commits all prior initiated but uncommitted async_load ops an async group. Optionally, each token represents a tracked async load operation.
- `tlx.async_load_wait_group(tokens)`
Wait for completion of prior asynchronous copy operations. Optionally, each token represents a tracked async commit group operation.
An example usage:
```
tlx.async_load(input_ptr_offsets, buffer)
tlx.async_load_commit_group()
tlx.async_load_wait_group(tl.constexpr(0))
x = tlx.local_load(buffer)
```
> [TLX] tlx.async_load_commit_group and tlx.async_load_wait_group

- .gitignore
- python/src/ir.cc
- python/test/unit/language/test_tlx.py
- python/triton/tlx
- third_party/tlx/compiler/code_generator.py
- third_party/tlx/language/async_task.py
Instead of defining a new build function in td, I notice `setRequestedRegisters` is already available in generated code `build/cmake.linux-x86_64-cpython-3.11/include/triton/Dialect/TritonGPU/IR/Ops.h.inc` so I invoke it in TLX frontend.
Testplan:
`pytest python/test/unit/language/test_tlx.py::test_async_tasks`
TTGIR
```
module attributes {"ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, ttg.target = "cuda:90", "ttg.threads-per-warp" = 32 : i32} {
tt.func public @add2_warp_specialized_kernel(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("/data/users/daohang/fbtriton/python/test/unit/language/test_tlx.py":18:0), %arg1: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("/data/users/daohang/fbtriton/python/test/unit/language/test_tlx.py":18:0), %arg2: !tt.ptr<f32> {tt.divisibility = …
```
> [TLX] Add requested registers to tlx.async_task

- lib/Conversion/TritonToTritonGPU/CMakeLists.txt
- lib/Conversion/TritonToTritonGPU/TritonGPUConversion.cpp
- lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
- third_party/tlx/dialect/include/IR/TLXOps.td
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/mma_ops.py
Introducing a new IR op `tlx.release_layout` to downcast the layout of `async_dot` output to none to favor TTIR legalization. The TTGIR for a gemm kernel now looks like
```
tt.func public @tgt_kernel(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("test_tlx.py":354:0), %arg1: i32 {tt.divisibility = 16 : i32} loc("test_tlx.py":354:0), %arg2: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("test_tlx.py":354:0), %arg3: i32 {tt.divisibility = 16 : i32} loc("test_tlx.py":354:0), %arg4: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("test_tlx.py":354:0), %arg5: i32 {tt.divisibility = 16 : i32} loc("test_tlx.py":354:0)) attributes {noinline = false} {
%cst = arith.constant dense<0.000000e+00> : tensor<64x64xf32, #blocked> loc(#loc1)
%c0_i32 = arith.constant 0 : i32 loc(#loc1)
%0 = …
```
> [TLX] IR release_layout op

- python/test/unit/language/test_tlx.py
- third_party/tlx/compiler/code_generator.py
- third_party/tlx/language/async_task.py
This PR allows users set replicates for each async task. 
NOTE. Pre-commit run includes 3 unrelated formatting changes in test_tlx.
~~TODO. I will expose replicate_id to the captures of each partition.~~ => In another PR
Test plan.
`with tlx.async_task(num_warps=4, registers=100, replicate=2):` can produce TTIR as below (expected).
```
module {
tt.func public @add2_warp_specialized_kernel(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("/data/users/daohang/fbtriton/python/test/unit/language/test_tlx.py":18:0), %arg1: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("/data/users/daohang/fbtriton/python/test/unit/language/test_tlx.py":18:0), %arg2: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("/data/users/daohang/fbtriton/python/test/unit/language/test_tlx.py":18:0), %arg3: !tt.ptr<f32> …
```
> [TLX] Add replicates to tlx.async_task 

- python/src/ir.cc
- third_party/tlx/compiler/code_generator.py
With `registers` left default in `tlx.async_task`, we were passing an empty list to following code while we actually need it to go to the else-branch. This PR fixes it by passing None instead of empty list. Verifying by `pytest python/test/unit/language/test_tlx.py`
```
void WarpSpecializeOp::setRequestedRegisters(::std::optional<::llvm::ArrayRef<int32_t>> attrValue) {
auto &odsProp = getProperties().requestedRegisters;
if (attrValue)
odsProp = ::mlir::Builder((*this)->getContext()).getDenseI32ArrayAttr(*attrValue);
else
odsProp = nullptr;
}
```
> [TLX] Bug fix of async_task taking default requested registers

- README.md
- lib/Conversion/TritonToTritonGPU/TritonGPUConversion.cpp
- lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
- python/test/unit/language/test_tlx.py
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/mma_ops.py
`acc = tlx.async_dot_wait(tl.constexpr(0), acc)`
Wait for completion of prior asynchronous dot operations.
Examples:
```
acc = tlx.async_dot(a_smem, b_smem)
acc = tlx.async_dot_wait(tl.constexpr(0), acc)
tl.store(C_ptrs, acc)
```
Generated TTIR:
```
%28 = tlx.require_layout %4 : !ttg.memdesc<64x64xf32, #shared, #smem, mutable> -> !ttg.memdesc<64x64xf32, #shared1, #smem, mutable> loc(#loc13)
%29 = tlx.require_layout %5 : !ttg.memdesc<64x64xf32, #shared, #smem, mutable> -> !ttg.memdesc<64x64xf32, #shared2, #smem, mutable> loc(#loc13)
%30 = tlx.require_layout %cst_11 : tensor<64x64xf32> -> tensor<64x64xf32, #mma> loc(#loc13)
ttng.fence_async_shared {bCluster = false} loc(#loc13)
%31 = ttng.warp_group_dot %28, %29, %30 {inputPrecision = 0 : i32, isAsync = true} : !ttg.memdesc<64x64xf32, …
```
> [TLX] async_dot_wait

- README.md
- include/triton/Dialect/TritonGPU/IR/Dialect.h
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/HoistTMEMAlloc.cpp
- python/test/unit/language/test_tlx.py
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/mem_ops.py
TMEM load/store ops require the layout encoding of the RankedTensorType to be compatible with the set of layouts supported by TMEM. 
We expose the builder API to construct such a layout out of default blocked layout (by default default blocked layout is given to tensors when converting ttir to ttgir). Then for load, we give the result this compatible layout, and then release it to layout without encoding; for store, we require the layout of the input from no encoding to compatible encoding before feeding it into store op.
Since users are writing tlx manually, they can control where to call the ops so we don't need to run the pass to hoist ops out of loops.
Eventually this will depend on `require_layout` and `release_layout` to work properly. For now for testing purpose, I force them to be …
> [TLX] TMEM load/store ops

- python/test/unit/language/test_tlx.py
- third_party/tlx/compiler/code_generator.py
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/utility.py
Expose replica_id to frontend. Potential use case will be handling staged WS in GEMM (see example in README.md).
This PR implements it via env vars and verifies with a comprehensive unit test (see details in UT in-code comments) while alternative approaches of appending context variables are also discussed.
Since current version doesn't have issues shown by unit tests, we can revisit the alternative approach when there's a need in the future.
```
partition0(%arg7: !tt.ptr<f32> loc(unknown), %arg8: !tt.ptr<f32> loc(unknown), %arg9: i32 loc(unknown), %arg10: !tt.ptr<f32> loc(unknown), %arg11: i32 loc(unknown)) num_warps(4) {
%cst = arith.constant dense<0.000000e+00> : tensor<1024xf32, #blocked> loc(#loc1)
%2 = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32, #blocked> …
```
> [TLX] async_task_replica_id

- python/test/unit/language/test_tlx.py
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/mma_ops.py
- third_party/tlx/tutorials/pipelined-gemm-blackwell-tma.py
This PR routes `tlx.async_dot` to tcgen05 mma for Blackwell. It takes A and B from SMEM, and accumulate to D in TMEM. If no barrier is given, the compiler backend will automatically insert barrier allocation and waiting right after it, making it a "synchronous" op. If a barrier is given, users need to manually wait for the mbarrier properly (but the mma op will arrive-on the barrier asynchronously)
How it was tested locally, before layout propagation is ready:
- We first need the same local patch as https://github.com/facebookexperimental/triton/pull/165 to force require/release out to be replaced by convert_layout for TMEM load/store 
- We then need this few tweaks to have `tlx.local_alloc` just give nv_mma_shared_layout right from the beginning (so we don't need to convert it or …
> [TLX] tcgen05 mma op for Blackwell

- python/test/unit/language/test_tlx.py
We now have require/release layout op so it's all working: 
```
pytest -vs python/test/unit/language/test_tlx.py::test_tmem_load_store
============================================================================================= test session starts =============================================================================================
platform linux -- Python 3.11.13, pytest-8.3.4, pluggy-1.5.0 -- /data/users/pchen7e4/miniconda3/bin/python
cachedir: .pytest_cache
rootdir: /data/users/pchen7e4/triton
configfile: pyproject.toml
plugins: xdist-3.7.0, forked-1.6.0, typeguard-4.3.0
collected 3 items …
```
> [TLX] enable test cases for tmem load/store

- .pre-commit-config.yaml
- python/test/unit/language/test_tlx.py
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/mem_ops.py
- third_party/tlx/language/mma_ops.py
- third_party/tlx/tutorials/pipelined-gemm-blackwell-tma.py
Refactoring tlx.async_dot implementation:
- Removing some unused parameters
- Removing the `mmav5` flag, instead computing it on the fly
- Tweaking layout requiring logics.
> [TLX] Refactor tlx.async_dot implementation

- lib/Dialect/TritonGPU/Transforms/Pipeliner/SoftwarePipeliner.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeliner/WGMMAPipeline.cpp
For an AsyncWaitOp op that does not come in with a valid token, the pipeliner could kick in optimizing its pending wait count to 0. This is problematic if the original op has a different pending count, even for loops with num_stages=0. I'm disabling the optimization. 
An upstreaming of the change is : https://github.com/triton-lang/triton/pull/7317 . As discussed there, there seems to be some fundamental problems to get existing optimizations working or bailing out for user-optimized code, but I think we should try to fixes those and see how far we can go. This patch is an attempt.
Also backporting Manman's previous work to disable WGMMA pipelining for loops with num_stages==0
```
python3 third_party/tlx/tutorials/pipelined-gemm.py
✅ Triton and Torch match
M …
```
> [TLX] Reduce the inference with the software pipeliner

- third_party/tlx/dialect/lib/Transforms/PropagateLayout.cpp
Scalar ops like `%c0_i32 = arith.constant 0 : i32` are used for indexing and should be skipped during layout propagation.
> [TLX] Skip scalars in layout propagation

- python/test/unit/language/test_tlx.py
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/mem_ops.py
Slicing along the innermost dimension from 128xN TMEM.
.ttir
```mlir
#blocked = #ttg.blocked<{sizePerThread = [1, 64], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
#blocked1 = #ttg.blocked<{sizePerThread = [1, 16], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
#loc = loc("/data/users/pchen7e4/triton/python/test/unit/language/test_tlx.py":278:0)
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 64, unpacked = true>
#tmem1 = #ttng.tensor_memory_encoding<blockM = 128, blockN = 16, unpacked = true>
module attributes {tlx.has_explicit_local_mem_access = true, tlx.has_tlx_ops = true, "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, ttg.target = "cuda:100", "ttg.threads-per-warp" = 32 : i32} {
tt.func public @tmem_subslice_kernel(%arg0: …
```
> [TLX] TMEM subslice op

- lib/Dialect/TritonGPU/Transforms/WarpSpecialization/AutomaticWarpSpecialization.cpp
- test/TLX/attach-metadata.mlir
- third_party/tlx/dialect/include/IR/Dialect.h
- third_party/tlx/dialect/lib/Transforms/Fixup.cpp
If the kernel has manual WS calls via TLX, we mark it on the module op as an attribute and leverage that to disable automatic ws pass (for Blackwell)
Testing: lit test and `pytest -vs python/test/unit/language/test_tlx.py` (test_async_tasks was failing and now passing)
> [TLX] Disable automatic warp spec for TLX

- third_party/tlx/compiler/code_generator.py
- third_party/tlx/language/types.py
Fixing two issues related to  `tl.async_task(replicate=2)`
- scoping each compilation of the task region; otherwise their live-ins and scoped vars would be mixed
- implement `_flatten_ir` for buffered tensors
> [TLX] Fixing issues for tl.async_task(replicate=2)

- third_party/tlx/dialect/lib/Transforms/PropagateLayout.cpp
- third_party/tlx/language/mem_ops.py
- third_party/tlx/language/types.py
This PR contains some hacky patches in layout propagation to unblock TLX kernels. 
`python third_party/tlx/tutorials/gemm-WS-hopper.py`
`python -m pytest third_party/tlx/tutorials/flash-attention-WS-pipelined-hopper.py`
> [TLX] Hacky fix in layout propagation to unblock

- third_party/tlx/language/mem_ops.py
- third_party/tlx/language/mma_ops.py
- third_party/tlx/language/types.py
When processing loops, `_unflatten_ir` is requires to reconstruct the original python type. Adding a wrapper, i.e, `buffered_tensor_type` for `buffered_tensor` object so that correspondingly. Otherwise `tl.blocked_type` would be used during `_unflatten_ir` which could lead to type mismatch. Similar is done for `mbarrier`.
> [TLX] Add a wrapper type for blocked tensors

- python/test/unit/language/test_tlx.py
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/mem_ops.py
- third_party/tlx/language/mma_ops.py
The only known good use case for now is to reuse TMEM buffer with a different data type so we only expose dtype to frontend.
This PR also:
- Extract `require_tmem_layout_unpacked` to force the tmem layout to have correct `unpacked` value
- Require `D` in MMA to have `unpacked == true` as specified in PTX
We still need temporary hack for layout propagation to get this to work.
```diff
diff --git a/third_party/tlx/dialect/lib/Analysis/LayoutPropagation.cpp b/third_party/tlx/dialect/lib/Analysis/LayoutPropagation.cpp
index 6983ccb4a..15c3db986 100644
--- a/third_party/tlx/dialect/lib/Analysis/LayoutPropagation.cpp
+++ b/third_party/tlx/dialect/lib/Analysis/LayoutPropagation.cpp
@@ -4,6 +4,7 @@
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include …
```
> [TLX] memdesc reinterpret

- python/triton/runtime/cache.py
Fix issues https://fb.workplace.com/groups/385893200869952/permalink/724909593634976/
Test plan: 
- delete `/tmp/triton_cache_daohang/` entirely
- run a good unit test
- introduce bad code changes and run the same unit test
> [TLX] Include compiler and language path in triton cache key

- README.md
- include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
- python/test/unit/language/test_tlx.py
- test/Conversion/tritonnvidiagpu_to_llvm.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/BarrierOpToLLVM.cpp
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/barrier.py
- third_party/tlx/tutorials/flash-attention-WS-pipelined-pingpong-hopper.py
Adding `tlx.named_barrier_wait` and `tlx.named_barrier_arrive` to supporting Pingpong schedule. Two ttgir ops are introduced correspondingly. Also adding WS+pipelined+Pingpong FA kernel.
```
After:
fused-attention-ws-pipelined-pingpong-batch4-head32-d128:
N_CTX  Triton [FP16]
0   1024.0     488.167798
1   2048.0     576.562504
2   4096.0     603.177504
3   8192.0     619.294642
4  16384.0     614.810779
Before:
fused-attention-ws-pipelined-batch4-head32-d128:
N_CTX  Triton [FP16]
0   1024.0     478.080941
1   2048.0     556.157572
2   4096.0     527.902147
3   8192.0     595.027327
4  16384.0     600.218371
```
> [TLX] Support named barrier for Pingpong schedule

- test/TLX/propagate-layout.mlir
- third_party/tlx/dialect/lib/Analysis/LayoutPropagation.cpp
This change skips the layout propagation for registers. `require_layout` ops on tensor types will be rewritten into `convert_layout` ops, and following passes will handle them.
> [TLX] Skip tensors in layout propagation

- python/triton/language/semantic.py
- third_party/tlx/dialect/lib/Transforms/PropagateLayout.cpp
- third_party/tlx/language/mem_ops.py
- third_party/tlx/language/types.py
- third_party/tlx/tutorials/pipelined-gemm.py
A previous hacky patch creates NVMMA layout encoding by default to make WGMMA work in our WS kernels
https://github.com/facebookexperimental/triton/commit/c4d476f6cce272df09b3d4d01a4f966a9ed9265f 
It failed two tests:
- pytest python/test/unit/language/test_tlx.py::test_local_load where `tlx.local_alloc` creates 1-D buffer not for WGMMA
- python third_party/tlx/tutorials/pipelined-gemm.py where 2D SMEM buffer is created and used by WGMMA but not in WS
The reason why we overlooked this is discussed at https://fb.workplace.com/groups/385893200869952/permalink/724909593634976/. We should revisit how TLX changes are picked up by Triton cache key generation. A VERY IMPORTANT takeaway is to use `TRITON_ALWAYS_COMPILE=1` each time you run a test to avoid incorrect cache hit.
Back to this PR: …
> [TLX-main] Bug fix in layout encoding

- third_party/tlx/tutorials/gemm-WS-blackwell.py
Optimization techniques applied:
- Warp Specializations: 1 producer group loading data async with TMA, 1 MMA consumer group issuing async MMA operations, 1 epilogue consumer group storing result from TMEM to GMEM
- Persistent kernel: each program processes more than 1 tile and stay in the same SM for as long as possible. This hides latency of epilogue consumer group's store operation
- TMA load/store: with host side descriptor initialization
- Epilogue sub-tiling: have the epilogue group store results half by half to reduce SMEM pressure
Performance:
```bash
Locking GPU 5 power cap to 750 W
Locking GPU 5 frequency cap to 1965 Hz
...
✅ Triton and Torch match
Running benchmarks...
M       N       K       cuBLAS       Triton
0    256.0   256.0   256.0     4.619278 …
```
> [TLX] Blackwell WS GEMM tutorial kernel

- python/test/unit/language/test_tlx.py
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/mem_ops.py
This is to support preloading a tensor to SMEM and use it piece-by-piece later on. An example use case of the feature is:
```
desc_in = tl.make_tensor_descriptor(
input_ptr,
shape=[1, M * N],
strides=[M * N, 1],
block_shape=[1, BLOCK_SIZE_M * BLOCK_SIZE_N],
)
buffers_in = tlx.local_alloc((1, BLOCK_SIZE_N), tl.int16, BLOCK_SIZE_M)
buffer_in = tlx.local_view(buffers_in, 0)
reinterpreted = tlx.local_reinterpret(buffer_in, tl.int16, [1, BLOCK_SIZE_M * BLOCK_SIZE_N])
tlx.async_descriptor_load(desc_in, reinterpreted, [0, off_m * N + off_n], bar)
for k in range(0, BLOCK_SIZE_M):
buffer_in = tlx.local_view(buffers_in, k)
....
```
Without using the `local_reinterpret` the  `async_descriptor_load` would get the wrong shape.
> [TLX] Allow local_reinterpret to change shapes

- third_party/tlx/language/mem_ops.py
test_tlx.py is full of such errors:
```
Argument of type "buffered_tensor | mbarrier" cannot be assigned to parameter "result" of type "buffered_tensor" in function "async_load"
Type "buffered_tensor | mbarrier" cannot be assigned to type "buffered_tensor"
"mbarrier" is incompatible with "buffered_tensor"
```
because local_view returns a type union but subsequent usage of its return value usually only expects one of the two possible types.
This PR will teach linter to recognize a proper return type given a param type.
> [TLX] Improve type hints for local_view

- python/src/ir.cc
- python/test/unit/language/test_tlx.py
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/barrier.py
- third_party/tlx/language/mem_ops.py
- third_party/tlx/language/types.py
Adding `to_ir`, `_flatten_ir_types` and `mangle` implementation to `buffered_tensor` so that it can be used for function calls. Also unifying `buffered_tensor` an `buffered_tensors`.
> [TLX] Refactor types to support inlining

- python/test/unit/language/test_compile_errors.py
#227 changed some exception wrapping behavior and now these tests are failing because they're supposed to check the "__cause__" of the CompilationError instead of CompilationError itself.
This PR fixes them by letting `format_exception` also include stack traces of original `cause` exceptions, just like what's printed on console when error occurs.
`pytest -vs python/test/unit/language/test_compile_errors.py` now all pass.
> [TLX] Fix failed test due to CompilationError wrapping

- python/test/unit/language/test_tlx.py
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/tlx/mma_ops.py
This syncs these few PRs over from tlx branch:
- https://github.com/facebookexperimental/triton/pull/236
`pytest -vs python/test/unit/language/test_tlx.py` all pass.
> Pick #236 [TLX] Expose use_d flag of tcgen05 mma

- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/tlx/mma_ops.py
Token was used for dep analysis in some passes but now since TLX opens up things users could manually manage those ops. There's currently no usecase for exposing the token here so removing it from TLX API.
In particular, a pass that would require a token is `HoistTMEMAlloc` and it was disabled when we have tlx ops called in kernel https://github.com/facebookexperimental/triton/pull/198
`pytest -vs python/test/unit/language/test_tlx.py` all passing.
> [TLX] Remove token for Blackwell dot

- third_party/tlx/language/tlx/mma_ops.py
We were having
`acc_handle = require_tmem_layout_unpacked(acc, True, _builder)` to force unpacked to be True for D. Somehow it got broken later and the use of `acc_handle` was replaced by `acc.handle`. This PR fixes it back.
It didn't really break things by far because by default we give TMEM layout `unpacked = True`. 
https://github.com/facebookexperimental/triton/blob/ab3269eeb918a1af2ddeb562d51fff8d60bb1869/third_party/tlx/language/tlx/types.py#L104-L108
> [TLX] Fix blackwell dot D layout

- lib/Dialect/TritonNvidiaGPU/Transforms/OptimizeDescriptorEncoding.cpp
- test/TritonNvidiaGPU/optimize_descriptor_encoding.mlir
With TLX, we have two problems:
- We might have WS ops that tensordesc layout propagation pass does not recognize, because WS ops can be created earlier than that pass now
- We might have TTNG TMA load/store ops created earlier than that pass (previously TMA lowering is later so that pass only needs to recognize tt descriptor load/store ops)
This PR fixes it with these changes:
- When seeding tensor desc layout, support `ttng::AsyncTMACopyLocalToGlobalOp` and `ttng::AsyncTMACopyGlobalToLocalOp`. Due to the nature of these ops, we can get "desired shared mem layouts" from the op itself directly (unlike `tt.descriptor_load` that needs to infer that from the users of the result distributed tensor).
- When propagating layouts, always tie args of all regions together. e.g. If we want to change …
> [TLX] fix tensordesc layout propagation

- python/test/unit/language/test_tlx.py
- python/triton/compiler/code_generator.py
With TLX the kernel is going to be more verbose and it's easier to accidentally shadow a variable in a loop.
The current check for this behavior does not understand types like `tensor_descriptor` or `tlx.buffered_tensor`. If the type is not `triton.tensor` it will be allowed.
This PR tightens the check.
Without this PR, the issue will surface only at building ttir and it's a lot harder to narrow down the issue on a non trivial kernel:
```
python/test/unit/language/test_tlx.py::test_loop_carry_var_check /data/users/pchen7e4/triton/python/test/unit/language/test_tlx.py:1292:22: error: 'scf.for' op 0-th region iter_arg and 0-th yielded value have different type: '!ttg.memdesc<2x16x16xi16, #ttg.nvmma_shared<{swizzlingByteWidth = 32, transposed = false, elementBitWidth = 16}>, …
```
> [TLX] loop carry check

- python/test/unit/language/test_tlx.py
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/tlx/types.py
When building a func call, we need to give the arg the right mem space attr instead of always forcing SMEM.
`pytest -vs python/test/unit/language/test_tlx.py` all passing.
> [TLX] propagate mem space to func calls properly

- python/src/gluon_ir.cc
Summary: getNumRegions() returns 2, even though getPartitionRegions().size() is more than 2.
Without the fix, we will hit "Op region index out of range".
> Fix a failure when creating more than 2 regions

- README.md
- python/test/unit/language/test_tlx.py
- third_party/tlx/language/tlx/mem_ops.py
- third_party/tlx/tutorials/gemm-WS-blackwell.py
- third_party/tlx/tutorials/pipelined-gemm-blackwell-tma.py
Fixing the return type of tmem local_load to be based on block_type instead of buffered_tensor type.
Also retiring storage specification for `tlx.local_load` and `tlx.local_store` as it can be inferred from the mem desc.
> [TLX] Fix tmem local_load return type

- python/triton/language/semantic.py
Cherry-pick #247 requires non-trivial merge conflict fix in pre-check. 
Manually applies the one-line fix as a new PR.
> [TLX-main] Fix dot_precheck to allow for tlx.buffered_tensor (copying #247)

- third_party/tlx/language/tlx/types.py
When we compare two `nv_mma_shared_layout_encoding` we should compare all the fields instead of directly comparing two objects.
```
> /data/users/pchen7e4/facebookexperimental/triton/python/triton/compiler/code_generator.py(930)_verify_loop_carried_variable()
-> assert loop_val.type == live_val.type, \
(Pdb) loop_val.type
buffered_tensor_<fp16, ['128', '128'], nv_mma_shared_layout_encoding, 0>
(Pdb) live_val.type
buffered_tensor_<fp16, ['128', '128'], nv_mma_shared_layout_encoding, 0>
(Pdb) live_val.type == loop_val.type
False
(Pdb) live_val.type.shape == loop_val.type.shape
constexpr[True]
(Pdb) live_val.type.layout == loop_val.type.layout
False
```
#225 broke `third_party/tlx/tutorials/flash-attention-WS-pipelined-pingpong-hopper.py` because it does not treat two types equal even if …
> [TLX] Fix nv_mma_shared_layout_encoding type comparison

- python/setup.py
Summary:
Currently we are having permission issue when run with root.
```
[55/283] Building Passes.h.inc...
FAILED: [code=126] third_party/amd/include/TritonAMDGPUTransforms/Passes.h.inc $SRC_DIR/python/build/cmake.linux-x86_64-cpython-3.10/third_party/amd/include/TritonAMDGPUTransforms/Passes.h.inc
cd $SRC_DIR/python/build/cmake.linux-x86_64-cpython-3.10 && /tmp/triton/.triton/llvm/llvm-a66376b0-ubuntu-x64/bin/mlir-tblgen -gen-pass-decls -name TritonAMDGPU -I $SRC_DIR/third_party/amd/include/TritonAMDGPUTransforms -I$SRC_DIR/include -I$SRC_DIR/. -I/tmp/triton/.triton/llvm/llvm-a66376b0-ubuntu-x64/include -I/tmp/triton/.triton/llvm/llvm-a66376b0-ubuntu-x64/include -I$SRC_DIR/include -I$SRC_DIR/python/build/cmake.linux-x86_64-cpython-3.10/include -I$SRC_DIR/third_party …
```
> Patch download file with chmod 777

- test/TLX/tlx-verifier.mlir
- third_party/tlx/dialect/lib/Transforms/Fixup.cpp
It will be problematic for ttgir conversion. Let's just throw error early and tell the TLX users to move the code into ws regions, which is also better for kernel perf.
Added a lit test. Also tested on blackwell with `./third_party/tlx/run_all.sh`
Run a real tlx kernel with such violations:
```
test_kernel.py:150:9: error: WarpSpecializeOp should not capture RankedTensorType. Try moving tensor computation into specific async task.
with tlx.async_tasks():
^
#blocked = #ttg.blocked< ...
...
```
It's more user friendly than previous error message:
```
error: 'ttg.warp_specialize' op partition region #0 argument #18 has type 'tensor<128xf32, #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [1], order = [0]}>>' but corresponding capture has type 'tensor<128xf32, …
```
> [TLX] Throw error early if WS captures RankedTensorType

- third_party/tlx/dialect/lib/Analysis/LayoutPropagation.cpp
- third_party/tlx/dialect/lib/Transforms/PropagateLayout.cpp
Also restricting layout propagation to memdesc only.
```
python third_party/tlx/tutorials/blackwell-gdpa.py
B=1024 max_M=1000 D=384 H=3 sparsity=0.5
GDPA TLX WS: 1.2268870290120442 ms
```
> [TLX] Do not overwrite unpacked for fp32 types during layout propagation

- python/test/unit/language/test_tlx.py
- third_party/tlx/language/tlx/compiler/code_generator.py
When default (program-level) `num_warps` is set to one, the compilation would fail with a tmem load or store used in a task region. This is because tmem load/store requires a region of 4 or 8 warps, and during the dry run of async_task compilation (mainly for computing variable captures), the global `num_warps` instead of region `num_warps`  is used. I'm fixing it by doing two dry-runs. The first one is to compute region information, followed by WS op creation, and the variable capturing is done in the second dry-run where region `num_warps`  is available.
> [TLX] Fix issues where default num_warps cannot be one with async_task

- python/triton/language/core.py
- python/triton/language/semantic.py
Easy fix. Not captured by TLX UTs until recently because we were just using semantic dot_precheck.
> [TLX-3.5] Fix a pre-existing tl.dot error introduced during rebase

- third_party/tlx/dialect/triton_tlx.cc
#297 introduces `is_async` in ttng::TCGen5MMAOp builder by default and fails Blackwell dot tests
```
FAILED python/test/unit/language/test_tlx.py::test_async_dot_blackwell - AssertionError: assert 1 == 2
FAILED python/test/unit/language/test_tlx.py::test_async_dot_blackwell_not_use_d - AssertionError: Tensor-likes are not close!
FAILED python/test/unit/language/test_tlx.py::test_tcgen05_commit - AssertionError: assert 4 == (1 + 4)
FAILED python/test/unit/language/test_tlx.py::test_async_dot_blackwell_tmem_A - AssertionError: Tensor-likes are not close!
============================================================= 4 failed, 22 passed, 76 skipped in 11.51s ==============================================================
```
> [TLX] set ttng::TCGen5MMAOp is_async when mBarriers not empty

- python/triton/compiler/code_generator.py
- python/triton/language/semantic.py
1. ValueError: Invalid rounding mode: <triton._C.libtriton.ir.builder object at 0x7fb740b150d0>. Supported rounding modes are 'rtne' and 'rtz'. Simple fix in `self.cast` function signature in semantics by cross-verifying between `git difftool 2ac060b8b 330c88bb3 -- python/triton/language/semantic.py`. But we need to factor out our own changes on dot_precheck so that future merge conflicts can be handled automatically in semantics.py
2. AssertionError: Loop-carried variable "i" has initial type constexpr_type[0] but is re-assigned to constexpr_type[1] in loop! Please make sure that the type stays consistent.
3. Fix create_dot(): incompatible function arguments
`pytest python/triton_kernels/tests/test_matmul.py::test_op`
> [TLX-3.5] Fix pytest python/triton_kernels/tests/test_matmul.py::test_op

- lib/Conversion/TritonToTritonGPU/TritonGPUConversion.cpp
- python/test/unit/language/test_tlx.py
- test/TLX/rewrite-local-alias.mlir
- third_party/amd/backend/compiler.py
- third_party/nvidia/backend/compiler.py
- third_party/tlx/dialect/include/IR/Dialect.h
- third_party/tlx/dialect/include/IR/TLXInterfaces.td
- third_party/tlx/dialect/include/IR/TLXOps.td
- third_party/tlx/dialect/include/IR/Traits.h
- third_party/tlx/dialect/include/Transforms/Passes.td
- third_party/tlx/dialect/lib/Analysis/LayoutPropagation.cpp
- third_party/tlx/dialect/lib/IR/CMakeLists.txt
- third_party/tlx/dialect/lib/IR/Traits.cpp
- third_party/tlx/dialect/lib/Transforms/CMakeLists.txt
- third_party/tlx/dialect/lib/Transforms/RewriteLocalAlias.cpp
- third_party/tlx/dialect/triton_tlx.cc
- third_party/tlx/language/tlx/mem_ops.py
- third_party/tlx/tutorials/blackwell-gdpa.py
With this PR users now can create two separate logic local memory buffers and alias them so they eventually share the same physical buffers. This allows a different separate memory layout is attached to each logic buffer
User can specify such memory aliasing through the `reuse` operand of `tlx.local_alloc`
```
a_tiles = tlx.local_alloc((BLOCK_M, BLOCK_K), tl.float16, tl.constexpr(1))
c_tiles = tlx.local_alloc((BLOCK_N, BLOCK_N), tl.float16, tl.constexpr(1), reuse=a_tiles)
```
In this case, `c_tiles` and `a_tiles` two logically-separate but physically-shared buffers. The size of the physical buffer is the max size of them. The underlying layout propagation pass will atomically figure out a memory layout for each logical buffer separately.
> [TLX] Introduce local allocation aliasing for local buffer reuse

- test/TLX/propagate-layout.mlir
- third_party/tlx/dialect/lib/Analysis/LayoutPropagation.cpp
Allow `MemDescTransOp` to operate on an uninitialized lattice for the case where it is not followed by a `RequiredLayout` op.
Aslo adding the gdpa kernel lit test.
> [TLX] Fix a layout propagation issue

- test/Analysis/test-allocation.mlir
- test/Conversion/tritonnvidiagpu_to_llvm.mlir
1. Some inline PTX operations were switched to NVVM intrinsics in cfe3dd079865d9f23cc6d7854de707636892cacf
2. Extending the live ranges of allocations in changes the allocation offsets (63df6d4d710929f530efa5418699ae5ceb34d818)
> Fix lit tests

- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSCodePartition.cpp
Moving buffer creation logics earlier so that smem/tmem allcoation will be hoisted to the top of a kernel, for a better handling for downstream passes.
A smem channel like below 
```
scf.for %arg25 = %c0_i32 to %9 step %c1_i32  : i32 {
%30 = tt.descriptor_load %arg4[%29, %c0_i32] {ttg.partition = 4 : i32} 
%31 = ttg.local_alloc %30 {ttg.partition = 4 : i32} 
%59 = ttng.tc_gen5_mma %31, %56, %result[%arg32], %false, %true {loop.cluster = 0 : i32, loop.stage = 2 : i32, tt.self_latency = 1 : i32, ttg.partition = 3 : i32}
```
now becomes:
```
%0 = "ttg.local_alloc"() : () 
scf.for %arg25 = %c0_i32 to %9 step %c1_i32  : i32 {
%51 = "tt.descriptor_load"(%arg4, %50, %16) <{cache = 1 : i32, evict = 1 : i32}> {ttg.partition = 4 : i32} : 
%52 = "arith.constant"() <{value = 0 : i32}> 
%53 = …
```
> [WS] Moving buffer creation earlier

- python/triton/compiler/compiler.py
Add dbg print requested by internal use case but pushed back when upstreaming
https://github.com/triton-lang/triton/pull/6802/commits/3eaff6f111643482ce7a134715aec05d596f58b7
Re-land https://github.com/facebookexperimental/triton/pull/333 to sidestep sync issues
> [FB][Reland #333] Add dbg prints when overriding IR by users

- test/Hopper/WarpSpecialization/1D_tmem.mlir
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/TMEMAlloc1D.cpp
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/TMEMUtils.h
Adds support for the reinterpret logic to enable looking at a slice of a buffer. Here is an example input:
```
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, unpacked = true>
#blocked = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
#blocked1 = #ttg.blocked<{sizePerThread = [1, 1], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [1, 0]}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 0, transposed = true, elementBitWidth = 32, CTAsPerCGA = [1], CTASplitNum = [1], CTAOrder = [0]}>
#shared1 = #ttg.nvmma_shared<{swizzlingByteWidth = 0, transposed = false, elementBitWidth = 32}>
#shared2 = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [0]}>
#smem = #ttg.shared_memory
module attributes …
```
> [autoWS] Add TMEM Buffer Reinterpret Helper + Integrate into existing 1D Buffer Logic

- test/Hopper/WarpSpecialization/1D_tmem.mlir
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/TMEMAlloc1D.cpp
The existing expand dims logic only works because the input was always feeding into another expandDims. To make this robust to other possible 1D changes (or slight variations in the IR where the exact TMEM channel is in a different location) this supports generating the expandDims with any blocked encoding.
Before the expand dims this generates this IR:
```
%7 = ttg.convert_layout %6 : tensor<128xf32, #blocked> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #blocked1}>>
```
which creates a new blocked layout and inserts the convert layout.
> [AutoWS] Make 1D TMEM logic robust for expand dims

- include/triton/Dialect/TritonGPU/Transforms/Schedule.h
- lib/Dialect/TritonGPU/Transforms/Pipeliner/ScheduleLoops.cpp
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization.cpp
The existing structure of loop scheduling will fail to run on the second pass of any persistent kernels because it fails to meet the loop scheduling preconditions.
In particular, the loop scheduler requires the following details to update the schedule from the existing one:
1. It must be an inner loop
2. It must have the tt.warp_specialize attribute
3. It must have the tt.max_stage defined (indicates the scheduler already ran).
At this stage our outer loop satisfies condition 2 and the inner loop satisfies conditions 1 and 3. This adds a preprocessing step to update the inner loop to contain the `tt.warp_specialize` attribute so loop scheduling can proceed and adds loop scheduling to the main loop (before token lowering).
You can see the output of running `triton-opt …
> [AutoWS] Enable loop scheduling on the inner of loop(s) of persistent FA after WS

- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization.cpp
Moves Loop Scheduling after Token Lowering, which is a requirement because all operators are required to have a provided stage for pipelining. This eliminates the error that says: `error: 'ttg.memdesc_index' op not assigned a pipeline stage`.
> [AutoWS] Move Loop Scheduling logic after Token Lowering

- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSCodePartition.cpp
For this case, we need to create gen5_commit before the consumer release, and the insertion point for the consumer release should be after the forOp.
> [autoWS] fix handling of a channel where consumer is gen5 mma inside the loop

- lib/Dialect/TritonNvidiaGPU/Transforms/TMALowering.cpp
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSCodePartition.cpp
TMALowering currently incorrectly allows a TMA store to reuse an existing allocation even if the contents of that allocation may have changed. For example, our WS implementation currently generates the following sequence:
```
%acc = local_load
%barr = memdesc_index
arrive_barrier %barr
descriptor_store %acc
```
which gets transformed into:
```
%barr = memdesc_index
arrive_barrier %barr
async_tma_copy_local_to_global
```
Here, the TMA operation now reads from the allocation after we have executed the "consumer release" barrier.
To address this, track TMA stores when inserting barriers and ensure that the consumer release is inserted after the TMA store. This allows us to make the optimisation in TMALowering simple and safe.
> Fix merging TMA store with SMEM buffer

- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSCodePartition.cpp
For column-major tensors that'll be stored out in row-major way by TMA store, if they are in different tasks, we currently create a column-major smem buffer. The producer populates in a natural way and the consumer converts it to row-major in registers before throwing it to TMA store. This will end up a pattern where the convert layout is folded into the TMA store, e.g,
```
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#shared2 = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = true, elementBitWidth = 16}>
ttng.async_tma_copy_local_to_global %desc_o_29[%qo_offset_y_42, %c0_i32_35] %103 : !tt.tensordesc<tensor<128x128xf16, #shared>>, !ttg.memdesc<128x128xf16, #shared2, #smem, mutable> loc(#loc129)
```
Unfortunately, the TMA store …
> [autoWS] Fix local buffer layout to favor TMA store

- lib/Dialect/TritonGPU/Transforms/Pipeliner/ScheduleLoops.cpp
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/CodePartitionUtility.cpp
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/CodePartitionUtility.h
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/TMEMAlloc1D.cpp
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSCodePartition.cpp
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSLowerMem.cpp
Adds an assert that all latency ops have stage info and forces the propagation in places to fix accuracy.
> [AutoWS] Add an assert that all latency ops have a corresponding stage/cluster and propagate missing barrier info

- include/triton/Dialect/TritonGPU/Transforms/Schedule.h
- lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeliner/Schedule.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeliner/ScheduleLoops.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeliner/SoftwarePipeliner.cpp
The pipelining steps will still execute for partitions with a single stage. This will result in unnecessary epilogue generation, hurting performance. Here is an example with the producer epilogue in DP FA:
Before: [P1979886251](https://www.internalfb.com/phabricator/paste/view/P1979886251)
After: [P1979906182](https://www.internalfb.com/phabricator/paste/view/P1979906182)
> [AutoWS] Prune pipelining for Partitions with a single stage
